name: Publish Notion website to GitHub Pages

on:
  # Manual update only.
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout loconotion
        uses: actions/checkout@v2
        with:
          repository: leoncvlt/loconotion
          path: loconotion
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          path: pages_repo

      - name: Build Loconotion docker image
        run: docker-compose build loconotion
        working-directory: loconotion
        
      - name: Run Loconotion
        run: |
          docker run \
          -v "$GITHUB_WORKSPACE/pages_repo/dist:/app/loconotion/dist" \
          -v "$GITHUB_WORKSPACE/pages_repo/site.toml:/app/loconotion/site.toml" \
          loconotion "site.toml"
        working-directory: loconotion

      - name: Add Google Analytics tracking code
        run: |
          echo '<script async src="https://www.googletagmanager.com/gtag/js?id=YOUR_ANALYTICS_ID"></script>
          <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag("js", new Date());

            gtag("config", "YOUR_ANALYTICS_ID");
          </script>' >> $GITHUB_WORKSPACE/pages_repo/dist/index.html
          
          sed -i 's/YOUR_ANALYTICS_ID/UA-275137883-1/g' $GITHUB_WORKSPACE/pages_repo/dist/index.html
        working-directory: pages_repo
      
      - name: Push to GitHub pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          GIT_DEPLOY_DIR=dist/site \
          GIT_DEPLOY_BRANCH=gh-pages \
          GIT_DEPLOY_REPO="https://${{ github.token }}@github.com/${{ github.repository }}.git" ./deploy.sh
        working-directory: pages_repo
